FROM node:alpine as builder
WORKDIR '/app'
# copy package and lock
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
# as react listens on 3000
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /user/share/nginx/html
